### ISSUE TITLE
The consistency of the function names

### ISSUE THREAD

**Issue by Leo-Lee15** [abresler/requestsR#1]
Thanks for creating the fantastic `requestsR` package!

I noticed that the naming methods is very inconsistent. While  `Get`, `Head`, `Options`  are capitalized,  `delete`, `post`, `put` are not. The may be a consideration of avoiding namespace conflicts. But I think a consistent naming method is better and that an upper-case version of the functions (`delete`, `post`, `put`) may be better.

**Comment by abresler** [comment]
Something to consider, and you are correct I did that for namespace reasons.

**Comment by abresler** [comment]
Though I don't love title case I think you are right and it's best to be consistent, did that so please reinstall
